version: '2'
services:
  loftusheatingandac:
    build: .
    ports:
     - "1337:1337"
    volumes:
     - ".:/usr/src/app/"
    environment:
      NODE_ENV: 'development'
      PORT: 1337
      MONGOLAB_URI: mongodb://root:password@mongo:27017/loftusheatingandac?authSource=admin
    entrypoint: pm2-runtime app.js --watch
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: loftusheatingandac
    volumes:
      - "./init_mongo:/docker-entrypoint-initdb.d"
    ports:
      - "27017:27017"