version: '2'
services:
  loftusheatingandac:
    build: .
    ports:
     - "1337:1337"
    volumes:
     - ".:/usr/src/app/"
    environment:
      NODE_ENV: 'production'
      PORT: 1337
      MONGOLAB_URI: "mongodb://heroku_app22294212_A:n3AELsw46Q4PLza@cluster-app22294212.lu9rm.mongodb.net:27017/heroku_app22294212"
    #entrypoint: pm2-runtime app.js --watch
    entrypoint: node app.js