version: '2'
services:
  loftusheatingandac:
    build: .
    ports:
     - "1337:1337"
    volumes:
     - ".:/usr/src/app/"
    environment:
      NODE_ENV: 'development'
      PORT: 1337
    entrypoint: pm2-runtime app.js --watch